Klimatbyran/klimatkollen

pages/kommun/[municipality]/[step].tsx

> Shallow routing allows you to change the URL without running data fetching methods again, that includes [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props), [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching/get-static-props), and [getInitialProps](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props).
https://nextjs.org/docs/routing/shallow-routing
Luckily!

fix: Animations and SEO-friendly links now work together

---

pages/index.tsx
pages/kommun/[municipality]/[step].tsx
pages/kommun/[municipality]/index.tsx

There is no need for it: https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops-or-api-routes

chore: Do not use API endpoints

---

components/Map.tsx
components/Municipality.tsx

Map shows whole country now:
Show same figure in score card as in total:
Start sliders on current year instead of 2021 (which can not be changed since it has already happened)

feat: zoom on map on startpage reverted to show the whole country.

---

components/Footer.tsx

bytte länk till wwf:s parisavtalalssida + ändrade copy ang hur koldioxidbudgeten beräknas

fix wwf link + CO2 budget copy

---

pages/index.tsx

Fix för att font-storleken för utsläppsprocenter på kartan blir för stora på mobil.
OBS! Testa innan den deployas på Vercel - borde se OK ut men kunde själv bara testa på dator inte mobil!

set percent font smaller for mobile

---

README.md

"Issues" and "Pull Requests" seem broken when clicked from [the repo](https://github.com/Klimatbyran/klimatkollen) - they resolve to incorrect paths like, eg. https://github.com/Klimatbyran/klimatkollen/blob/main/issues instead of https://github.com/Klimatbyran/klimatkollen/issues.

Absolute path for links in Readme

---

components/Municipality.tsx

There was a bit of confusion regarding which year to start counting the budget. Mats reported that it should be 2020, not 2019. This PR fixes that.

fix: Use 2020 instead of 2019 as starting point

---

components/Map.tsx

La till klammer som försvann i senaste merge-konflikten på Maps!

Quick-fix: add tag that went missing on latest Map merge-conflict

---

components/Map.tsx

Ny vända med begränsningar i kartan. Nu tagit bort dem igen pga funkar inte på mobilen, måste hitta sätt så att det blir bra både på desktop och mobil.

remove viewstate constraints bc not mobile friendly atm

---

components/Map.tsx

För att fix #92 
Har provat på desktop och iPhone och funkar fint för mig. 
Förstår dock inte varför det explicit skrivits att det inte ska gå att zooma innan så undrar om det kan finnas ngn anledning till det. Får gärna testas av ngn annan också innan merge.

Make map zoomable on desktop

---

package.json

Setting NEXT_PUBLIC_MAILCHIMP_URL to dummy url when running dev script
The instructions claim that 
$ yarn
$ yarn dev
is all that is required to start the project locally. Not so, because NEXT_PUBLIC_MAILCHIMP_URL is required.

Inject NEXT_PUBLIC_MAILCHIMP_URL with dummy value in dev script.

---

components/Footer.tsx

Removed non-commerical from Creative commons license link in footer

---

components/Graph.tsx

Solves  #370.
It seems the "default" animations of chart.js only work if the dataset is visible at all times, although we can visually hide it, as done in this PR. It feels a bit sketchy, but its the quickest way to fix the issue.

Fix 370 Animate Paris Agreement graph

---

components/DropDown.test.ts
components/DropDown.tsx

When I started searching for Stockholm, I noticed that the municipality typeahead/autocomplete dropdown behaved in a really weird way:
As a user, I'd prefer if results that start with my search query are ranked higher.
This PR improves two things:
- Municipalities are now properly sorted before they're fed into the search. If no locales are explicitly passed to localeCompare(), it defaults to the user's locale. My machine and browser are both in English, so the sorting got whacky. I think an explicit `'sv'` would be better, since we're dealing with Swedish municipalities.
- The search filter is now smarter, taking into consideration results that start with the query.
With the fix:

Improve the existing municipality search – sorting by Swedish and prioritizing matches that begin with the input query

---

utils/datasetDefinitions.tsx

Rearrange datasets on homepage, grouping emission related datasets on top. Also arranging them so that they take up less space on mobile screens.
From this
to this

Rearrange emission datasets on homepage

---

pages/index.tsx

Decrease map/list title size for mobile screens. From
to
Fix #439

Decrease map/list title size for mobile screens

---

package-lock.json
package.json

After this change, `npm audit` reports zero vulnerabilities. It seems to work for me, but could someone else please also verify that no bugs are introduced with this change?

Update to latest deck.gl, removing vulnerabilities Fixes #324

---

doc/contributing.md

I'm trying to describe how to make a PR as well as good "rules of engagement" or something along those lines. The intention is to balance several different needs from different roles, including volunteer's need for transparency and guidance, and core team's need for efficiency and control.
I appreciate feedback but preferably with limited [bikeshedding](https://producingoss.com/en/common-pitfalls.html#bikeshed) ;)

#421 contributing.md first draft

---

components/ToggleSection.tsx

Remove default arrow from toggle section plus minor cleanup.
Please test on actual mobile device!
Used to look like this:
Now like this on my iPhone:

Remove default arrow from toggle section

---

public/locales/sv/common.json
utils/datasetDefinitions.tsx

Change consumption related emissions boundaries from [7, 6.7, 6.4, 6.1, 5.8] to [6.4, 6.2, 6, 5.8, 5.6] in order to make map reflect acceptable levels.
Fix #365

lower thresholds for consumption related emissions

---

components/Footer/FooterNewsletterForm.tsx
public/locales/sv/common.json

Add a hidden label to the newsletter signup form to ensure it complies with WAI-ARIA standards. It passed my WAI-ARIA Firefox extension check, but there could potentially be a more elegant solution, as this is not my strong suit.

add hidden label to newsletter form

---

data/tests/test_climate_requirements_in_procurements.py

The sampled input data in the test file went out of sync with what the caluclation expects.
I grabbed the additional inputs by first running the calculation as per the instructions in `data/README.md`, then extracted it from the output like so:
```bash
cat output/climate-data.json | jq '.[] | select(.kommun | IN("Ale", "Alingsås", "Bräcke")) | {kommun: .kommun, procurementLink: .procurementLink}'
```
Fixes #460

Fix the calculate_procurement_score test

---

components/Map/Map.tsx

Prevents map from moving away from Sweden. Tested on MacOS w/ Firefox and Android w/ Firefox.

[#462] restrain map to Swedish coordinates

---

components/DatasetButtonMenu.tsx
pages/index.tsx

fix #518 
Right now a user can't navigate with keyboard to choose the different datasets due to the radio button input having display none and therefore is not accessible for assistive technologies. 
This solution uses native buttons instead of the custom styling of radio buttons, which have built in support for accessible navigation. 
There is now a lot of guidelines online on how to code more accessible and to meet requirements of the new [EU Accessibility Act](https://www.w3.org/TR/epub-a11y-eaa-mapping/) coming into place summer 2025.
Official accessibility guidelines: https://www.w3.org/WAI/standards-guidelines/wcag/

refactor: make radio button menu into accessible button menu

---

__tests__/index.test.tsx
components/FactSection.tsx
components/Municipality/ScorecardSection.tsx
components/ToggleSection.tsx

Fix #533 and make `ToggleSection` easier to press by increasing the clickable area.
Also fixed a broken test.

Fix/533 remove extra arrows for iOS details element

---

components/ComparisonTable.tsx
components/FactSection.tsx
components/Municipality/ScorecardSection.tsx
utils/createCompanyList.tsx

This makes it more obvious there is more info available for each row.
I experimented with two alternatives, and based on feedback from people I asked, alternative 2 seems to be the best. Alternative 2 is now implemented.

Feature: Add expand icon to comparison table to improve UX

---

components/PillSwitch.tsx
pages/[dataGroup]/[dataset]/[dataView]/index.tsx
pages/api/map.tsx
pages/api/municipalities.tsx
pages/in-english/index.tsx
pages/index.tsx
pages/kallor-och-metod/index.tsx
pages/kommun/[municipality]/[step].tsx
pages/om-oss/index.tsx
pages/partierna/index.tsx
pages/utslappsberakningar/index.tsx
utils/climateDataService.tsx
utils/companyDataService.tsx
utils/datasetDefinitions.tsx
utils/shared.ts

This PR improves the perceived performance when navigating between data groups (companies vs municipalities), among other bugfixes and improvements related to the routing and data loading. Thanks to improved server side caching, data loads faster too, while using less RAM due to reduced duplication in the cache. 
- Bugfix: Ensure state from URL can control which dataGroup to show by default. This allows linking to the RegionalView again.
- Simplify client-side state and rely on server side state plus link prefetching instead. This reduces the unnecessary re-renders on the client when navigating between different datasets.
- Add caching for municipalities and companies since they are the heavy datasets. Remove response caching since that duplicates data unnecessarily and thus uses more …

Refactor and bugfixes: Improve routing, state management and caching for dataViews

---

components/Header.tsx
components/ToggleButton.tsx
utils/devices.ts

Fix #549 
Fix #562 
- Ensure consistent header height for all screen sizes. This in turn fixes the scroll padding used for navigating to anchor links, and account for the fixed header.
- Ensure consistent positioning for the hamburger menu button. They are now always positioned on top of each other.
- Improve breakpoints and simplify so we only have one approach (min-width), to make it easy to design for mobile first.
- Allow pressing the Escape key to close the hamburger menu on desktop devices.
- Show the desktop navigation menu earlier (at 1024px instead of at 1440px). This gives a better experience for laptop/desktop users.
- Improve vertical alignment for klimatkollen logo to feel visually centered.

Improve UX for the main menu 

---

components/Map/Map.tsx
utils/generateMunipacitySitemap.ts
utils/shared.ts

This can be done because special characters for all names have already been replaced in the data file that is actually used (`pages/data/kommuner.json`).
This will first and foremost reduce confusion (I got confused why we had two kommuner.json in the project). And this will also give a slight performance improvement since we don't need to perform useless operations.
I did a global search for all the special characters that `replaceLetters()` is replacing and confirmed that these characters are no longer present in the project. And if we need this formatting for some reason in the future, we can search the git history, GitHub etc to get the `replaceLetters()` helper back.
Also, here's a script I created because I accidentally worked with the wrong dataset where strings were malformed: …

Remove old pulbic data file, and remove use of replaceLetters()

---

data/climate_data_calculations.py

Add all numeric columns to historical emissions in climate data calculations so that this doesn't need to be hardcoded with future updates from SMHI.

add all numeric columns to historical emissions

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/task.md

I Identified two kinds - Task and Bug Report. I hope these suggestion questions should help issue authors more clearly express their expectations, and leave more helpful information for those that take the issues up. Let me know if you think the questions included are decent, or if you'd like to suggest some alternatives.

Add an issue template for better issues.

---

public/locales/sv/common.json
utils/datasetDefinitions.tsx

Make the emission reduction colors more representative for the actual state of (serious lack of) emission reductions. Also use even numeric spans between the boundary values, to make the scale show the spread of values instead of heavily skewing towards grouping most municipalities in the later ranges.
The emissions map for municipalities was previously completely misrepresenting the data, and minimizing how serious the gap is between what is needed and what has happened so far.
The old map used the ranges `0, 0-1%, 1-2%, 2-5%, 5-10% and 10-15%`. This made most municipalities with far too low emission reductions to show up in the 2-5% or 5-10% ranges, when they color-wise actually should end up in the first ranges to match if their emissions reductions are enough or not. This might look …

Fairly represent the spread of values for the emission map by improving the boundaries.

---

data/climate_data_calculations.py
data/solutions/cars/electric_car_change_rate.py

Added command line parameter to climate_data_calculation.py to enable calculation of percentage values for the electric vehicle metrics. If '-t' is passed, then values will be converted to percentages (instead of 0.072, the number will be 7.2). An -o parameter was also added to specify the output filename. If -t is omitted, the original value is kept. If -o is omitted the default filename is output/climate_data.json.

added CLI params to control outfile and percentage value calc

---

public/locales/sv/common.json

Change bike land per capita year from 2022 to 2023 in dataset definitions.

Deploy hotfix to production

---

utils/createMunicipalityList.tsx

Fixes #643 
I noticed that we have a sorting function for the binary column in `Klimatplanerna` and also noticed that `Upphandlingarna` actually has no binary first-column, but rather a ternary (Ja/Nej/Kanske). The weird thing is that sorting by one column at a time works without a problem, but sorting by multiple columns does not sort the `Kommun` column.
Adding a simple sorting function for the `index`-column `Ställer krav` seems to work here. Note that I decided to go for the `formattedDataPoint`, because this sorts the string values (Ja/Nej/Kanske) instead of the `dataPoint` (2/0/1), which results in the same sorting as we currently have.

fix: add sorting function for procurementDemands to fix multi-sort in `Upphandlingarna`

---

pages/_document.tsx

Fix for #673 
Reproduced this on my phone and it solved the problem. Not entirely sure if I added the code at the correct location, though.

Disable automatic detection of possible phone number on mobile browsers

---

data/README.md
data/issues/emissions/cache_utilities.py
data/issues/emissions/historical_data_calculations.py
data/pyproject.toml
data/requirements.txt

Closes #682 by adding a test profiling tool, a faster excel parser and a DataFrame caching decorator. Reduces test suite execution time from 15 seconds to 8 seconds on first run and 0.3 seconds on second run when tested on a Mac Air M1.

Speed up data processing

---

pages/[dataGroup]/[dataset]/[dataView]/index.tsx
utils/companyDataService.tsx
utils/createCompanyList.tsx
utils/types.ts

* fetch company data fram api
* run lint
* change from scope2 lb to mb
* minor cleanup
* fix type error and linting
* add support for 0 and undefined scope values
* fix ts error
* fix error in graph component
* remove unrelated files
* add support for tags
* support edge cases with combined scope 1 n 2 emissions
* correct operator
* Use native `fetch()` which is stable since Node.js 21.0 (We're using 22 in prod)
* Update logic for selecting different values
* Improve error
* Allow preview for mid-cap companies
* Reduce data sent to client
---------

Production deployment: fetch company data fram api (#704)
