- pages/index.tsx
> chore: add paragraph under H1 at startpage

- pages/kommun/[municipality].tsx
My push to fix this in #19 must have failed without me noticing 🙈
> fix: Don't scroll when changing step

- components/Map.tsx
Added names to map when user hover over municipalities
> add municipality name on hover

- components/Footer.tsx
Use the preferred style of abbreviating it (with hyphens) and adding a [rel to the link](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#attr-license).
> Clarify license of the website

- components/Footer.tsx
Bytte hej@klimatkollen.se till hej@varabarnsklimat.se eftersom den första inte fungerar atm
> replace hej@klimatkollen w hej@varbarnsklimat until previous works again

- components/Map.tsx
Added constraints to map viewState so user can't toss map out of wrapper again. Unsure why that was commented out but a real nice feature!
> added constraints to map viewState so user can't toss map out of wrapper

- pages/index.tsx
Ändrade tillbaka så font inte blir mindre för liten skärm, tittar på andra lösningar för radbrytningar på kartans procent
> revoke change in percent font size

- README.md
Fixed broken(relative) link in README.md
> Fixed link to klimatkollen.se in README.md

- components/Map.tsx
- package-lock.json
- package.json
La till progressbar när man klickat på kommun, märkt att det ofta tar ett tag att ladda den datan och ville lägga till ngt som får användaren att förstå att klicket registrerats.
> add progress bar when municipality loading

- package.json
- pages/_app.tsx
Set NEXT_PUBLIC_GA_ID=G-XXXXXXXXXX in hosting environment to enable tracking
> Added Google Analytics tracking

- components/Layout.tsx
Adds `nav` to site, making it possible to easily access both pages.
> feat: deploy nav

- components/Graph.tsx
Tog bort kommunnamn på grafens y-axel
> rm municipality name from graph axis

- components/Municipality.tsx
Mer enhetlig/lättförståelig copy på grafsidan.
> kt -> tusen ton

- components/Municipality.tsx
> make Din plan legend line -> dot

- components/Map.tsx
> fix for faulty municipality lines

- components/Footer.tsx
Increase margin between footer contact links
Fix #208
> Increase footer link margin

- components/Municiplaity/Municipality.tsx
- components/Municiplaity/MunicipalityIssues.tsx
- components/Municiplaity/ScoreCard.tsx
- components/Typography.ts
- data/dataset_descriptions.tsx
Copy changes, including cement deduction text
> Update site copy (#223)

- components/Layout.tsx
- pages/index.tsx
> Fix/update margins (#276)

- components/shared.tsx
- pages/in-english/index.tsx
- pages/om-oss/index.tsx
* optimize img loads
* resize images
> Fix/slow loading images (#310)

- README.md
- pages/in-english/index.tsx
> update discord link

- .gitignore
- components/Footer/FooterNewsletterSubscribe.tsx
- package.json
The dev mailchimp env var hack is cool but doesn't work in powershell. Let's instead just not throw an exception on if the url is missing.
> don't throw on missing mailchimp + gitignore intellij

- pages/om-oss/index.tsx
fixed the extra comma with /lalarus
> fixed extra comma /lalarus

- utils/datasetDescriptions.tsx
https://github.com/Klimatbyran/klimatkollen/issues/386
> Move datasets Elbilarna and Laddarna closer together (#386)

- components/BackArrow.tsx
- components/Municipality/Municipality.tsx
- components/Typography.ts
Adresses #363
- Better display on mobile
- Center municipality name
- Center divs in HeaderSection
> Improve municipality screen

- components/Typography.ts
> decrease municipality titles/headers for mobile screens

- components/Graph.tsx
Decrease the dot size for the approximated data graph on the municipality page to better suit mobile view
> Decrease the dot size for the approximated data graph

- components/FactSection.tsx
- components/ToggleSection.tsx
- pages/om-oss/index.tsx
> Fix 390 dropdown tab navigation

- components/ToggleSection.tsx
Import arrow colors in toggle section from color theme
> Import toggle section arrow colors from theme

- pages/index.tsx
- utils/createMunicipalityList.tsx
- utils/datasetDescriptions.tsx
Fix type error in municipality list plus minor cleanup
> Fix type error in municipality list

- __tests__/utils/generateMunipacitySitemap.test.ts
Test expected urls like "www.klimatkollen.se/kommun/Municipality" which should be "www.klimatkollen.se/kommun/municipality", ie lowercase
> Fix broken sitemap test

- __tests__/utils/generateMunipacitySitemap.test.ts
- components/FactSection.tsx
- components/Graph.tsx
- components/Map/Map.tsx
- components/Municipality/MunicipalityEmissionNumbers.tsx
- components/ToggleSection.tsx
- pages/index.tsx
- pages/om-oss/index.tsx
- pages/sitemap.xml.ts
- public/robots.txt
- utils/createMunicipalityList.tsx
- utils/datasetDescriptions.tsx
- utils/generateMunipacitySitemap.ts
- utils/shared.ts
New styling of municipality graph to better suit mobile view, new columns in climate plan list, tabbable navigation, copy updates and some minor improvements. Also sitemap + test for sitemap.
> New styling of municipality graph, new columns climate plans, tabbable navigation, sitemap, copy updates

- pages/index.tsx
- utils/createMunicipalityList.tsx
Fix so that datasets have correct list column headers
> Correct dataset list headers

- .prettierrc
- Atoms.tsx
- package-lock.json
- package.json
- pages/_app.tsx
Seems like this was added 2 years ago and isn't used any more.
> Remove unused dependency

- utils/datasetDefinitions.tsx
Update third procurement list column copy
> Update procurement list column copy

- README.md
Cleaned up readme, reorganized some sections and added better advice on contributing.
> Brush up readme

- README.md
This is a suggestion to give a quick overview of the project. There are different perspectives, so I describe it from looking at "the data", "The files"; and "the software components". Curious to see if people like this approach.
> Some overviews to help see the big picture

- __tests__/utils/generateMunipacitySitemap.test.ts
- pages/kommun/[municipality]/[step].tsx
- pages/kommun/[municipality]/index.tsx
- pages/sitemap.xml.ts
- utils/generateMunipacitySitemap.ts
- utils/politicalRuleService.tsx
Add en- and decoding to municipality routing as well as minor cleanup
Fix #469
> add en- and decoding to municipality routing

- next.config.js
Quick cleanup to match recommended setup from `next-i18n-next`
> Remove duplicate i18n config

- doc/getting-started.md
> 514: npm run ci -> npm ci

- components/Footer/Footer.tsx
- public/locales/sv/common.json
- fixes #486 by adding information to footer regarding who runs Klimatkollen.
- Cleans up footer code using markdown component
> Website footer update

- Dockerfile
- README.md
- compose.yml
* fixes broken docker file
* move to docker-compose to allow for live-refresh
> Adds docker compose

- components/PageWrapper.tsx
Reintroduce 12px padding to sides of table in compact mode of PageWrapper
> reintroduce 12px padding to sides of table

- data/climate_data_calculations.py
- data/solutions/cars/electric_car_change_rate.py
Added command line parameter -n <#> and functionality to truncate all floating point numbers to the defined number of decimals. Default is -1 and no truncation.
> Climate data calc decimals

- data/README.md
> Update data readme with correct path to emissions calculations

- styles/globals.css
- utils/createCompanyList.tsx
> Use monospace font to make it easier to compare numbers in the company list

- components/InfoModal.tsx
> Ensure InfoModal shows on top of other elements on the page

- utils/shared.ts
> Update cache expiration time to match the intended value

- pages/in-english/index.tsx
- public/locales/sv/about.json
Update Christian's intro texts to being an advisor to Swedish Government (not Minister of Innovation).
> update christian's intro texts

- README.md
- doc/contributing.md
- doc/getting-started.md
* Update docs to include frontend technologies implementation
* Update docs to include recommended learning prerequisites and resource
* Fixes #607: Update contributing.md to include relative markdown link to getting-started.md
* Fixes #607: Fix README.md Contributing section link
* Remove 'frontend technologies' from getting-started.md meant for Klimatbyran/beta; fix typos in contributing.md
> Feat/update docs (#663)

- pages/[dataGroup]/[dataset]/[dataView]/index.tsx
- utils/companyDataService.tsx
- utils/shared.ts
- utils/types.ts
- Show all companies in the list view by default (#714)
- Improve handling of unreported values in the `scope1And2` column
- Improve handling of unreported values in the `scope3` column
fix #713
> Production deployment for legacy frontend
